// List of US states and abbreviations
export const usStates = [
  { name: "Alabama", abbreviation: "Alabama" },
  { name: "Alaska", abbreviation: "Alaska" },
  { name: "Arizona", abbreviation: "Arizona" },
  { name: "Arkansas", abbreviation: "Arkansas" },
  { name: "California", abbreviation: "California" },
  { name: "Colorado", abbreviation: "Colorado" },
  { name: "Connecticut", abbreviation: "Connecticut" },
  { name: "Delaware", abbreviation: "Delaware" },
  { name: "Florida", abbreviation: "Florida" },
  { name: "Georgia", abbreviation: "Georgia" },
  { name: "Hawaii", abbreviation: "Hawaii" },
  { name: "Idaho", abbreviation: "Idaho" },
  { name: "Illinois", abbreviation: "Illinois" },
  { name: "Indiana", abbreviation: "Indiana" },
  { name: "Iowa", abbreviation: "Iowa" },
  { name: "Kansas", abbreviation: "Kansas" },
  { name: "Kentucky", abbreviation: "Kentucky" },
  { name: "Louisiana", abbreviation: "Louisiana" },
  { name: "Maine", abbreviation: "Maine" },
  { name: "Maryland", abbreviation: "Maryland" },
  { name: "Massachusetts", abbreviation: "Massachusetts" },
  { name: "Michigan", abbreviation: "Michigan" },
  { name: "Minnesota", abbreviation: "Minnesota" },
  { name: "Mississippi", abbreviation: "Mississippi" },
  { name: "Missouri", abbreviation: "Missouri" },
  { name: "Montana", abbreviation: "Montana" },
  { name: "Nebraska", abbreviation: "Nebraska" },
  { name: "Nevada", abbreviation: "Nevada" },
  { name: "New Hampshire", abbreviation: "New Hampshire" },
  { name: "New Jersey", abbreviation: "New Jersey" },
  { name: "New Mexico", abbreviation: "New Mexico" },
  { name: "New York", abbreviation: "New York" },
  { name: "North Carolina", abbreviation: "North Carolina" },
  { name: "North Dakota", abbreviation: "North Dakota" },
  { name: "Ohio", abbreviation: "Ohio" },
  { name: "Oklahoma", abbreviation: "Oklahoma" },
  { name: "Oregon", abbreviation: "Oregon" },
  { name: "Pennsylvania", abbreviation: "Pennsylvania" },
  { name: "Rhode Island", abbreviation: "Rhode Island" },
  { name: "South Carolina", abbreviation: "South Carolina" },
  { name: "South Dakota", abbreviation: "South Dakota" },
  { name: "Tennessee", abbreviation: "Tennessee" },
  { name: "Texas", abbreviation: "Texas" },
  { name: "Utah", abbreviation: "Utah" },
  { name: "Vermont", abbreviation: "Vermont" },
  { name: "Virginia", abbreviation: "Virginia" },
  { name: "Washington", abbreviation: "Washington" },
  { name: "West Virginia", abbreviation: "West Virginia" },
  { name: "Wisconsin", abbreviation: "Wisconsin" },
  { name: "Wyoming", abbreviation: "Wyoming" },
];

export const skillOptions = [
  { value: "Adaptive", label: "Adaptive" },
  { value: "Creative", label: "Creative" },
  { value: "Problem-Solving", label: "Problem-Solving" },
  { value: "Patience", label: "Patience" },
  { value: "Teamwork", label: "Teamwork" },
  { value: "Compassion", label: "Compassion" },
  { value: "Communication", label: "Communication" },
  { value: "Leadership", label: "Leadership" },
];
